language: java

jdk: oraclejdk8

services:
  - docker

addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESSKEY

env:
  - DB=mysql
  - DB=mariadb

before_script: ./travis_before_script.sh

script: ./travis_script.sh

after_script: ./travis_after_script.sh

notifications:
  irc: 
    channels:
      - "chat.freenode.net#openmrs"
    on_failure: always
    on_success: change
