language: java

jdk: oraclejdk8

services:
  - docker
  
cache:
  directories:
    - $HOME/.m2

addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESSKEY

env:
  - DB=mysql
  - DB=mariadb
  
install: true

script: ./travis_script.sh

after_script: ./travis_after_script.sh

notifications:
  irc: 
    channels:
      - "chat.freenode.net#openmrs"
    on_failure: always
    on_success: change
