services:
  # Proxy
  proxy:
    build: ./proxy
    ports:
      - 80:80

  # Microfrontends
  frontend:
    ports:
      - 8081:8080
    build: ./ui
    environment:
      SPA_PATH: /ui
      API_URL: /openmrs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ui"]
      timeout: 5s
    volumes:
      - ./distro/microfrontends:/var/www/ui/

  # OpenMRS:
  openmrs:
    ports:
      - 8080:8080
    build: openmrs/
    depends_on:
      - db
    environment:
      MODULE_WEB_ADMIN: "true"
      DB_AUTO_UPDATE: "true"
      DB_CREATE_TABLES: "true"
      DB_HOST: db
      DB_DATABASE: openmrs
      DB_USERNAME: ${OPENMRS_DB_USER}
      DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - ./distro/openmrs_core/openmrs-webapp.war:/usr/local/tomcat/webapps/openmrs.war
      - openmrs-data:/usr/local/tomcat/.OpenMRS/
      - ./distro/openmrs_modules:/usr/local/tomcat/.OpenMRS/modules/
      - ./distro/openmrs_config:/usr/local/tomcat/.OpenMRS/configuration/
      - openmrs-config-checksums:/usr/local/tomcat/.OpenMRS/configuration_checksums/
      - ./properties/openmrs:/etc/properties

  # MariaDB
  db:
    image: mariadb:10.3
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OPENMRS_DB_USER}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql

version: "3.7"
volumes:
  openmrs-data: ~
  db-data: ~
  openmrs-config: ~
  openmrs-config-checksums: ~
  openmrs-modules: ~
  openmrs-owas: ~
